[package]
name = "adnet-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11"
log = "0.4"
mio = { version = "1.0", features = ["net", "os-poll"] }
rand = { version = "0.8", features = ["small_rng"] }
rand_pcg = "0.3"
rand_seeder = "0.3"
